# SPDX-License-Identifier: LGPL-2.1-or-later
# SPDX-FileNotice: Part of the Telemetry addon.

################################################################################
#                                                                              #
#   Â© 2025 FreeCAD Project Association                                         #
#                                                                              #
#   This addon is free software: you can redistribute it and/or modify         #
#   it under the terms of the GNU Lesser General Public License as             #
#   published by the Free Software Foundation, either version 2.1              #
#   of the License, or (at your option) any later version.                     #
#                                                                              #
#   This addon is distributed in the hope that it will be useful,              #
#   but WITHOUT ANY WARRANTY; without even the implied warranty                #
#   of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.                    #
#   See the GNU Lesser General Public License for more details.                #
#                                                                              #
#   You should have received a copy of the GNU Lesser General Public           #
#   License along with this addon. If not, see https://www.gnu.org/licenses    #
#                                                                              #
################################################################################


name : Unit Tests


permissions:

    contents : read


on:
    pull_request:

        branches : [ main ]

    push:

        branches : [ main ]


jobs:
    test:

        runs-on : ubuntu-latest

        steps:

            -   name : Checkout Repository
                uses : actions/checkout@v6

            -   name : Setup Python
                uses : actions/setup-python@v6
                with :
                    python-version-file : pyproject.toml

            -   name : Setup UV
                uses : astral-sh/setup-uv@v7
                with :
                    version : 0.9.27

            -   name : Install Project
                run : uv sync --locked

            -   name : Execute Tests
                run : uv run --module unittest discover Tests
